import logging
import os
import sys
import time
import random
import numpy as np
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader
from typing import List, Dict, Any, Tuple, Optional
from enum import Enum
from abc import ABC, abstractmethod
from scipy.stats import norm
from scipy.spatial import distance
from scipy.optimize import minimize
from scipy.integrate import quad
from scipy.interpolate import interp1d
from scipy.special import erf
from scipy.stats import norm
from scipy.stats import uniform
from scipy.stats import expon
from scipy.stats import beta
from scipy.stats import binom
from scipy.stats import poisson
from scipy.stats import nbinom
from scipy.stats import geom
from scipy.stats import hypergeom
from scipy.stats import gumbel_r
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import gumbel_r
from scipy.stats import gumbel_max
from scipy.stats import weibull_min
from scipy.stats import pareto
from scipy.stats import lognorm
from scipy.stats import exponnorm
from scipy.stats import norminvgauss
from scipy.stats import invweibull
from scipy.stats import genpareto
from scipy.stats import